sudo: required
services:
  - docker

before_install:
  - docker build -t vivekraj59/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vivekraj59/docker-react npm run test

  deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-806866393353"
    bucket_path:"docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
    secure: "$AWS_ACCESS_KEY"
